version: '3.9'
services:

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prefect
      POSTGRES_DB: prefect
    ports:
      - "5432:5432"

  server:
    image: prefecthq/prefect:2-python3.11
    restart: always
    volumes:
      - prefect:/root/.prefect
    entrypoint: ["/bin/bash", "-c"]
    command: ["prefect server start --host 0.0.0.0"]
    ports:
      - "4200:4200"
    environment:
    - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:prefect@postgres:5432/prefect
    depends_on:
      - postgres

  flow:
    image: prefecthq/prefect:2-python3.11
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    command: ["sh", "-c", "sleep 1 && python work.py"] # wait just a sec for the server to start
    environment:
      - PREFECT_API_URL=http://server:4200/api
      - PREFECT_EXPERIMENTAL_ENABLE_EXTRA_RUNNER_ENDPOINTS=True
      - PREFECT_RUNNER_SERVER_HOST=127.0.0.1
    depends_on:
      - server
    ports:
      - "8080:8080"

volumes:
  prefect:
